name: nix-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build .
